# Generated by Django 6.0.4 on 2026-04-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posty.reply'),
        ),
    ]
