# Generated by Django 6.0.4 on 2026-05-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0005_post_user_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
