# Generated by Django 6.0.4 on 2026-05-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0006_section_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_image_path',
            field=models.CharField(default='/dupa', max_length=500),
            preserve_default=False,
        ),
    ]
