# Generated by Django 5.1.15 on 2026-05-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0007_image_thumbnail_image_path'),
        ('posty', '0007_post_favourites_alter_image_id_alter_post_id_and_more'),
    ]

    operations = [
    ]
