# Generated by Django 5.1.15 on 2026-05-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posty', '0007_alter_image_id_alter_post_id_alter_reply_id_and_more'),
        ('posty', '0010_remove_post_favorites_post_favourites'),
    ]

    operations = [
    ]
